apiVersion: apps/v1
kind: Deployment
metadata:
  name: configployment
  labels:
    team: yarismadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - image: gozdesaygiliyalcin/competitioncongif:v002
          name: podconfig
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 8888
