server:
  port: ${SERVERPORT}

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: main-service
  datasource:
    url: ${DBURL}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: ${AUTHURL}
    main: ${MAINURL}
    user: ${USERURL}