server:
  port: 9092

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/competitionDB'
    username: 'postgres'
    password: '2211223'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/auth-service/
    main: http://localhost:9092/main-service/
    user: http://localhost:9091/user-service/